# Why we cannot used regression for classification.
- 1. Best fit line changes because of outliers casing  Prediction goes wrong.
- 2. The outcomes comes > 1 and < 0 by squicing Technique.

# How Logistic Regression solve classification.
- The best fit line - $h_\theta(x) = \theta_0 + \theta_1 x_1$
- The above fit equation is transfoprmed by sigmoid activation function resulting to 0 and 1.
    - $ h_\theta(x) = \sigma(\theta_0 + \theta_1 x_1)$
    - $ h_\theta(x) = \frac{1}{1+e^(\theta_0+\theta_1x_1)} $

**Cost function of linear regression**
- $J (\theta_0, \theta_1) = \frac{1}{n}\sum_1^n(y_i - h_\theta(x)_i)^2$

**Logistic Regression Cost function**
- $J (\theta_0, \theta_1) = \frac{1}{n}\sum_1^n(y_i - h_\theta(x)_i)^2$

**Reason we don't used this above cost function because while ooptimizing we will stop in local minima instead of globa maxima because non convexcity nature of above cost function**

so, we used
**Log loss function**
- $J(\theta_1, \theta_0) = - y_ilog(h_\theta(x)_i)^2$

**Cost function**
- $J(\theta_1, \theta_0) = - y_ilog(h_\theta(x)_i) - (1-y_i)log(1-h_\theta(x) $

- $J(\theta_0,\theta_1)$ =$$ - log(h_\theta(x_i) if y=1 $$
$$                     = - log(1-h_\theta(x))  if y=0 $

## Logistic Regularization parameter
- $J(\theta_1, \theta_0) = - y_ilog(h_\theta(x)_i) - (1-y_i)log(1-h_\theta(x) + \lambda \sum_1^n (Slope)^2 + \lambda \sum_1^n|slope)| $

## Elastic Net 
- $J(\theta_1, \theta_0) = - y_ilog(h_\theta(x)_i) - (1-y_i)log(1-h_\theta(x) + \lambda_1 \sum_1^n (Slope)^2 + \lambda_2 \sum_1^n|slope)| $

- C is proportional to $\frac{1}{\lambda}$


# Performance metrics
-  Confusion Matrics:
               In case of binary classification, it is a 2x2 matrics having label with actual value and predicted value and each cell composed of correct prediction(TRUE POSITIVE), wrong prediction(TRUE NEGATIVE), FALSE POSITIVE, and FALSE NEGATIVE.
   - MODEl ACCURACY = $\frac{T_p + T_n}{T_p + F_p + T_n + F_n}$
   - Precession = $\frac{T_p}{T_p + F_p}$
        - Precession is used when  F_p is important.
   -  Recall = $\frac{T_p}{T_p +F_n}$
        - Recall is used when F_n is important
- $ F_Beta Score $  = $(1 + \beta^2)\frac{precission * Recall}{precission + Recall}$
   - If FP and FN are to important
   -  $When \beta =1 $
        - $ F_1 score  = 2 * \frac{P * R}{P + R}$

## Cross validation and its types
Let we have 1000 Datasets is divided into Training and Test sets. In thier are scenario we need to do split the training sets to validation and training sets for Hyperparameter tunning without repetation will it try best average accuracy.  
-  Its important because its used hyperparameter tunning.


Types of Cross Validation:
- 1.Leave One out Cross Validation : LEaving one out taking calculating accuracy, now 2nd record will leave one out calculating accuracyand soon.
    -  Disadvantage : Time complexity is huge, model tends to over fit

- 2. Kfold cross validation: k=5 mean five experience n= 500; exp1 first hundered, exp2 2nd hundred.. and soon.

- 3. stratified k fold cross validation (For Imbalanced datasets): Every split dataests have equal clases of target variable.

## Hyper parameter tunning with cross validation
- 1. Griv SearchCV: {GrivsearchCV + Cross Validation}. Its search    posiible combination.
     -  Disadvantage : Time complexcity increase with increase of datasets.
- 2. Random SearchCV: Here we randomly select no of iteration 

# Logistic Regression Implemenatation

In [1]:
from sklearn.datasets import load_iris
datasets = load_iris()

In [2]:
print(datasets.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [3]:
datasets.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
import pandas as pd
import numpy as np

In [5]:
df= pd.DataFrame(datasets.data, columns=datasets.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
df["target"]= datasets.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [7]:
df.target.unique()

array([0, 1, 2])

In [8]:
df_copy = df[df["target"]!=2]

In [9]:
df_copy['target'].unique()

array([0, 1])

In [10]:
## Independent and dependent features
X=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
classification=LogisticRegression(max_iter=200)

In [14]:
classification

LogisticRegression(max_iter=200)

In [15]:
classification.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [16]:
y_pred=classification.predict(X_test)

In [17]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

## Confusion Metrics,Accuracy,Classification Report

In [18]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [19]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]


In [20]:
print(accuracy_score(y_test,y_pred))

1.0


In [21]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Cross Validation

In [22]:
from sklearn.model_selection import KFold

In [23]:
cv=KFold(n_splits=5)

In [24]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [25]:
from sklearn.model_selection import cross_val_score

In [26]:
## these are the scores all the cross validation
scores=cross_val_score(classification,X_train,y_train,scoring='accuracy',cv=cv)

In [27]:
np.mean(scores)

1.0

In [28]:
## Lets see more complex data

# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [31]:
complex_class_model=LogisticRegression(max_iter=200)

In [32]:
complex_class_model.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [33]:
y_pred_complex=complex_class_model.predict(X_test)

In [34]:
print(confusion_matrix(y_test,y_pred_complex))
print(accuracy_score(y_test,y_pred_complex))
print(classification_report(y_test,y_pred_complex))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [35]:
## Cross Validatiuon
cv=KFold(n_splits=5)
cross_val_score(complex_class_model,X_train,y_train,cv=cv)

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])

In [36]:
## Lets see more complex data

# make a prediction logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

# Logisitic Regression Hyperparameter Tuning

In [37]:
## Lets see more complex data

# make a prediction logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

## Model Training Hyperparameter Tuning
## GridsearchCV

In [40]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [41]:
parameters={'penalty':('l1', 'l2','elasticnet'),'C':[1,10,20,30]}

In [42]:
classifier=LogisticRegression()

In [43]:
clf=GridSearchCV(classifier,param_grid=parameters,cv=5)

In [44]:
## Splitting of Training data to train and validation
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [45]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [46]:
clf.best_score_

0.8087500000000001

In [47]:
classifier=LogisticRegression(C=1,penalty='l2')

In [48]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [49]:
y_pred=classifier.predict(X_test)

In [50]:
y_pred=classifier.predict(X_test)

In [51]:
y_pred

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1])

In [52]:
classifier.predict_proba(X_test)

array([[0.71649202, 0.28350798],
       [0.19508969, 0.80491031],
       [0.12418141, 0.87581859],
       [0.05045906, 0.94954094],
       [0.88775659, 0.11224341],
       [0.75067497, 0.24932503],
       [0.97980488, 0.02019512],
       [0.3921745 , 0.6078255 ],
       [0.59920135, 0.40079865],
       [0.39295203, 0.60704797],
       [0.20428696, 0.79571304],
       [0.80257879, 0.19742121],
       [0.86422932, 0.13577068],
       [0.92665682, 0.07334318],
       [0.00131743, 0.99868257],
       [0.04171096, 0.95828904],
       [0.56288536, 0.43711464],
       [0.89322764, 0.10677236],
       [0.29278211, 0.70721789],
       [0.00870994, 0.99129006],
       [0.71879454, 0.28120546],
       [0.5108267 , 0.4891733 ],
       [0.76230298, 0.23769702],
       [0.73170811, 0.26829189],
       [0.10155737, 0.89844263],
       [0.04046512, 0.95953488],
       [0.57926768, 0.42073232],
       [0.00526468, 0.99473532],
       [0.03101648, 0.96898352],
       [0.96093035, 0.03906965],
       [0.

In [53]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [54]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



## Randomized Search cv

In [55]:
from sklearn.model_selection import RandomizedSearchCV

In [56]:
random_clf=RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5,n_iter=20)

In [57]:
random_clf

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [58]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [59]:
random_clf.best_params_

{'penalty': 'l2', 'C': 1}

# Logistic Regression Multi-class  Classification
- One Vs Rest (OVR) multiclass Classification:
   - M1(f1,f2,f3) : output feature f1
   - M2(f1,f2,f3) : output feature f2
   - M3(f1,f2,f3) : outyput feature f3
       - we will feature fi having more probability
       

In [60]:
# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)

In [61]:
# define the multinomial logistic regression model For multiclass classification
model = LogisticRegression(multi_class='ovr', solver='lbfgs')

In [62]:
# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [63]:
# trianing model
model.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [64]:
y_pred=model.predict(X_test)

In [65]:
model.predict_proba(X_test)

array([[9.10622335e-02, 5.88916888e-01, 3.20020878e-01],
       [7.74864218e-02, 8.83936419e-01, 3.85771592e-02],
       [6.84414416e-01, 2.03496841e-01, 1.12088744e-01],
       [1.43095699e-02, 9.01488946e-02, 8.95541536e-01],
       [6.87497205e-02, 8.36642893e-01, 9.46073865e-02],
       [1.09007702e-01, 3.07621844e-01, 5.83370453e-01],
       [3.78594000e-01, 2.08265604e-01, 4.13140396e-01],
       [3.14084906e-01, 1.75940674e-01, 5.09974420e-01],
       [5.14671931e-01, 1.90311178e-01, 2.95016891e-01],
       [5.97817613e-01, 3.02410459e-01, 9.97719283e-02],
       [4.20115939e-02, 3.31570100e-01, 6.26418306e-01],
       [4.86740270e-01, 1.04804858e-01, 4.08454873e-01],
       [8.01115911e-01, 3.37497449e-02, 1.65134344e-01],
       [8.98140961e-02, 6.97976196e-01, 2.12209707e-01],
       [7.29023255e-02, 8.39105805e-01, 8.79918698e-02],
       [5.10619176e-01, 2.09225440e-01, 2.80155384e-01],
       [1.24309039e-01, 7.90819633e-01, 8.48713286e-02],
       [3.42847759e-03, 3.71703

In [66]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[56 10 17]
 [16 41  6]
 [ 3 13 38]]
0.675
              precision    recall  f1-score   support

           0       0.75      0.67      0.71        83
           1       0.64      0.65      0.65        63
           2       0.62      0.70      0.66        54

    accuracy                           0.68       200
   macro avg       0.67      0.68      0.67       200
weighted avg       0.68      0.68      0.68       200

