In [1]:
import numpy as np

In [6]:
try:
    list(range(0.4, 10))
except Exception as e:
    print(e)

'float' object cannot be interpreted as an integer


In [10]:
list(np.arange(.4,10.4,1.5))

[0.4, 1.9, 3.4, 4.9, 6.4, 7.9, 9.4]

In [12]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [13]:
np.logspace(1,5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [17]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
arr = np.ones((3,4))

In [22]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
arr+5 # scalar operation

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [29]:
import  pandas as pd
pd.DataFrame(np.eye(3))

0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0

In [30]:
np.random.rand(2,3)

array([[0.55786282, 0.9184161 , 0.37835077],
       [0.95007767, 0.33303709, 0.55445303]])

In [33]:
np.random.randn(2,3) # rand random distributed data

array([[-0.24715126,  0.31787433, -1.53333365],
       [-1.56362573, -0.44344688, -0.6662801 ]])

In [40]:
arr = np.random.randint(1,5,(3,4))
arr

array([[2, 2, 1, 2],
       [2, 2, 1, 2],
       [2, 2, 4, 2]])

In [42]:
arr.reshape(6,2) # resahpe

array([[2, 2],
       [1, 2],
       [2, 2],
       [1, 2],
       [2, 2],
       [4, 2]])

In [43]:
try:
    arr.reshape(6,3)
except Exception as e:
    print(e)

cannot reshape array of size 12 into shape (6,3)


In [44]:
arr1 = np.random.randint(1,10, (5,6))
arr1

array([[6, 5, 2, 5, 4, 8],
       [7, 8, 1, 6, 1, 8],
       [2, 5, 9, 7, 6, 8],
       [5, 8, 5, 4, 6, 9],
       [4, 8, 1, 9, 1, 9]])

In [45]:
arr1 > 8

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False,  True],
       [False, False, False,  True, False,  True]])

In [47]:
arr1 [arr1 > 8]

array([9, 9, 9, 9])

In [51]:
arr1[0,[0,1]]

array([6, 5])

In [54]:
arr1

array([[6, 5, 2, 5, 4, 8],
       [7, 8, 1, 6, 1, 8],
       [2, 5, 9, 7, 6, 8],
       [5, 8, 5, 4, 6, 9],
       [4, 8, 1, 9, 1, 9]])

In [55]:
arr1[2:4,[2,3]]

array([[9, 7],
       [5, 4]])

In [56]:
arr1 = np.random.randint(1,3,[3,3])
arr2 = np.random.randint(1,3,[3,3])

In [57]:
arr1

array([[1, 1, 1],
       [1, 2, 1],
       [2, 2, 2]])

In [60]:
arr1 + arr2 # indexwise array operation

array([[3, 2, 3],
       [3, 4, 3],
       [3, 3, 3]])

In [61]:
arr1 - arr2

array([[-1,  0, -1],
       [-1,  0, -1],
       [ 1,  1,  1]])

In [ ]:
# MatriX multiplication in array


In [63]:
arr1 * arr2

array([[2, 1, 2],
       [2, 4, 2],
       [2, 2, 2]])

In [77]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
a = np.array([1,1,1,1])
arr+a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [86]:
b= np.array([[1,2,3]]) # Foe transpose we have nake it two dntion array 
arr+b.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [87]:
arr1

array([[1, 1, 1],
       [1, 2, 1],
       [2, 2, 2]])

In [88]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.        ],
       [1.        , 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.41421356]])

In [89]:
np.log(arr1)

array([[0.        , 0.        , 0.        ],
       [0.        , 0.69314718, 0.        ],
       [0.69314718, 0.69314718, 0.69314718]])

In [92]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.        ],
       [1.        , 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.41421356]])

In [93]:
np.mean(arr1), np.max(arr1)

(1.4444444444444444, 2)