# array manupulation

In [2]:
import numpy as np
arr = np.random.randint(1,10, (4,4))
arr

array([[2, 7, 4, 5],
       [4, 8, 2, 3],
       [9, 7, 1, 8],
       [8, 5, 2, 2]])

In [3]:
arr.reshape(8,2)

array([[2, 7],
       [4, 5],
       [4, 8],
       [2, 3],
       [9, 7],
       [1, 8],
       [8, 5],
       [2, 2]])

In [4]:
arr.T

array([[2, 4, 9, 8],
       [7, 8, 7, 5],
       [4, 2, 1, 2],
       [5, 3, 8, 2]])

In [5]:
arr.flatten()

array([2, 7, 4, 5, 4, 8, 2, 3, 9, 7, 1, 8, 8, 5, 2, 2])

In [7]:
np.expand_dims(arr, axis=0) 

array([[[2, 7, 4, 5],
        [4, 8, 2, 3],
        [9, 7, 1, 8],
        [8, 5, 2, 2]]])

In [9]:
data = np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [10]:
np.squeeze(data)

array([1, 2, 3])

In [11]:
np.repeat(data,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [13]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [14]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [15]:
arr1 = np.random.randint(1,10,(3 ,4))
arr2 = np.random.randint(1,10,(3 ,4))

In [16]:
arr1

array([[6, 7, 5, 6],
       [6, 4, 6, 2],
       [5, 8, 4, 9]])

In [17]:
arr2

array([[2, 5, 9, 9],
       [9, 7, 3, 1],
       [7, 9, 9, 4]])

In [18]:
arr1/arr2

array([[3.        , 1.4       , 0.55555556, 0.66666667],
       [0.66666667, 0.57142857, 2.        , 2.        ],
       [0.71428571, 0.88888889, 0.44444444, 2.25      ]])

In [19]:
arr1**arr2

array([[       36,     16807,   1953125,  10077696],
       [ 10077696,     16384,       216,         2],
       [    78125, 134217728,    262144,      6561]])

In [20]:
~arr1

array([[ -7,  -8,  -6,  -7],
       [ -7,  -5,  -7,  -3],
       [ -6,  -9,  -5, -10]])

In [21]:
arr1>arr2

array([[ True,  True, False, False],
       [False, False,  True,  True],
       [False, False, False,  True]])

In [ ]:
### string operation in numpy

In [27]:
arr = np.array(["abhi","rajkumar"])
arr

array(['abhi', 'rajkumar'], dtype='<U8')

In [28]:
np.char.upper(arr)

array(['ABHI', 'RAJKUMAR'], dtype='<U8')

In [29]:
np.char.capitalize(arr)

array(['Abhi', 'Rajkumar'], dtype='<U8')

In [30]:
# array mathematical function

In [31]:
arr1

array([[6, 7, 5, 6],
       [6, 4, 6, 2],
       [5, 8, 4, 9]])

In [32]:
np.sin(arr1)

array([[-0.2794155 ,  0.6569866 , -0.95892427, -0.2794155 ],
       [-0.2794155 , -0.7568025 , -0.2794155 ,  0.90929743],
       [-0.95892427,  0.98935825, -0.7568025 ,  0.41211849]])

In [34]:
np.tan(arr1)

array([[-0.29100619,  0.87144798, -3.38051501, -0.29100619],
       [-0.29100619,  1.15782128, -0.29100619, -2.18503986],
       [-3.38051501, -6.79971146,  1.15782128, -0.45231566]])

In [36]:
np.log(arr1)

array([[1.79175947, 1.94591015, 1.60943791, 1.79175947],
       [1.79175947, 1.38629436, 1.79175947, 0.69314718],
       [1.60943791, 2.07944154, 1.38629436, 2.19722458]])

In [37]:
np.exp(arr1)

array([[4.03428793e+02, 1.09663316e+03, 1.48413159e+02, 4.03428793e+02],
       [4.03428793e+02, 5.45981500e+01, 4.03428793e+02, 7.38905610e+00],
       [1.48413159e+02, 2.98095799e+03, 5.45981500e+01, 8.10308393e+03]])

In [39]:
np.power(arr1, 3)

array([[216, 343, 125, 216],
       [216,  64, 216,   8],
       [125, 512,  64, 729]], dtype=int32)

In [43]:
np.mean(arr1), np.median(arr1), np.std(arr1), np.var(arr1), np.min(arr1)

(5.666666666666667, 6.0, 1.7950549357115013, 3.222222222222222, 2)

In [44]:
# Array arithmatics operation

In [45]:
arr1

array([[6, 7, 5, 6],
       [6, 4, 6, 2],
       [5, 8, 4, 9]])

In [47]:
arr2 = np.array(np.random.randint(1,10,(3,4)))
arr2

array([[7, 6, 6, 1],
       [7, 5, 2, 7],
       [5, 7, 5, 3]])

In [48]:
np.multiply(arr1, arr2)

array([[42, 42, 30,  6],
       [42, 20, 12, 14],
       [25, 56, 20, 27]])

In [49]:
np.mod(arr1, arr2)

array([[6, 1, 5, 0],
       [6, 4, 0, 2],
       [0, 1, 4, 0]])

In [50]:
np.sqrt(arr1)

array([[2.44948974, 2.64575131, 2.23606798, 2.44948974],
       [2.44948974, 2.        , 2.44948974, 1.41421356],
       [2.23606798, 2.82842712, 2.        , 3.        ]])

In [51]:
# Numpy statistical function

In [54]:
np.mean(arr1), np.std(arr1), np.var(arr1)

(5.666666666666667, 1.7950549357115013, 3.222222222222222)

# Numpy part 4

In [63]:
arr = np.array(np.random.randint(1,100,15))
arr

array([ 2, 36, 92, 10, 17, 61, 69, 19, 49,  2, 16, 56, 65, 27, 75])

In [64]:
np.sort(arr)

array([ 2,  2, 10, 16, 17, 19, 27, 36, 49, 56, 61, 65, 69, 75, 92])

In [65]:
np.searchsorted(arr, 6)

1

In [68]:
np.count_nonzero(arr)

15

In [69]:
np.where(arr1>0)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [75]:
np.extract(arr1 > 0, arr)

array([ 2, 36, 92, 10, 17, 61, 69, 19, 49,  2, 16, 56])

In [ ]:
# Numy Byte Swapping

In [76]:
arr1

array([[6, 7, 5, 6],
       [6, 4, 6, 2],
       [5, 8, 4, 9]])

In [77]:
arr.byteswap() # arr.byeawp(True)

array([  33554432,  603979776, 1543503872,  167772160,  285212672,
       1023410176, 1157627904,  318767104,  822083584,   33554432,
        268435456,  939524096, 1090519040,  452984832, 1258291200])

In [78]:
arr1

array([[6, 7, 5, 6],
       [6, 4, 6, 2],
       [5, 8, 4, 9]])

In [80]:
a=np.copy(arr1)
a

array([[6, 7, 5, 6],
       [6, 4, 6, 2],
       [5, 8, 4, 9]])

In [81]:
b = arr.view()

In [82]:
b

array([ 2, 36, 92, 10, 17, 61, 69, 19, 49,  2, 16, 56, 65, 27, 75])

In [83]:
# view wil create swallow copy

In [84]:
# Numpy Matrix library

In [86]:
import numpy.matlib as nm

In [88]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [89]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [97]:
arr2 = nm.eye(3,4)
arr2

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [98]:
arr1

array([[6, 7, 5, 6],
       [6, 4, 6, 2],
       [5, 8, 4, 9]])

In [99]:
nm.dot(arr1, arr2)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)